language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
matrix:
    allow_failures:
        -
            php: 7
        -
            php: hhvm
cache:
    directories:
        - $HOME/.composer/cache
sudo: false
install:
    - 'travis_retry composer self-update 1.0.0-alpha11'
    - 'travis_retry composer global require "fxp/composer-asset-plugin:~1.1" "yiisoft/yii2-composer:~2.0"'
    - 'travis_retry composer global require "hiqdev/hidev:*@dev" "phpunit/phpunit:^4.8" "phpunit/phpunit-skeleton-generator:*" "fabpot/php-cs-fixer:*"'
    - 'travis_retry composer install --no-interaction'
    - '$HOME/.composer/vendor/bin/hidev travis/install'
script:
    - '$HOME/.composer/vendor/bin/hidev travis/script'
